env:
  browser: true
  jquery: true
  node: true
extends: "plugin:@wordpress/eslint-plugin/recommended-with-formatting"
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
